# Generated by Django 3.1.2 on 2021-04-07 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.CharField(choices=[('mobile', 'موبایل'), ('desktop', 'دسکتاپ')], default='NA', max_length=10)),
                ('browser', models.CharField(default='NA', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('day', 'روز'), ('week', 'هفته'), ('month', 'ماه')], default='NA', max_length=10)),
                ('view', models.IntegerField(default=0)),
                ('device', models.JSONField(null=True)),
                ('browser', models.JSONField(null=True)),
                ('user_repetitive', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField()),
                ('short', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
