# Generated by Django 3.1.2 on 2020-10-09 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20201008_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(choices=[('mobile', 'موبایل'), ('desktop', 'دسکتاپ')], default='NA', max_length=10)),
                ('browser', models.CharField(default='NA', max_length=50)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='report', to='app.url')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
