# Generated by Django 3.1.2 on 2020-10-09 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='report',
            name='device',
        ),
        migrations.RemoveField(
            model_name='report',
            name='viewer',
        ),
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(choices=[('mobile', 'موبایل'), ('desktop', 'دسکتاپ')], default='NA', max_length=10)),
                ('browser', models.CharField(default='NA', max_length=50)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', related_query_name='access', to='app.url')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', related_query_name='access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
