# Generated by Django 3.1.2 on 2020-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201009_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='browser',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='device',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('day', 'روز'), ('week', 'هفته'), ('month', 'ماه')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='user_repetitive',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
