# Generated by Django 3.1.2 on 2020-10-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201009_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user_repetitive',
            field=models.BooleanField(default=False),
        ),
    ]
